version: '3.4'

services:
  desafio.api:
    image: ${DOCKER_REGISTRY-}desafioapi
    build:
      context: .
      dockerfile: src/Desafio.Api/Dockerfile
  sqlServer:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlDesafio
    environment:
      - SA_PASSWORD=desafio123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - ./.Docker/Sql/Data:/var/opt/mssql/data
    ports:
      - "1433:1433"
  redis:
    image: redis
    container_name: redisDesafio
    command: redis-server --requirepass desafio123
    ports:
      - "6379:6379"